version: "2.3"

services:
    postgresql:
        image: postgres:9.6
        environment:
            POSTGRES_USER: vnext
            TZ: Asia/Tokyo
        ports:
            - 5432:5432
        volumes:
            - ./volumes/postgresql/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U vnext"]
            interval: 30s
            timeout: 30s
            retries: 3
        mem_limit: 500m